#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\AboutController::index
app_register:
  path: /register
  controller: App\Controller\RegistrationController::index
app_list:
  path: /list
  controller: App\Controller\ListController::index
app_add:
  path: /add
  controller: App\Controller\AddController::index
